parameters:
  codein.fieldtype.color.identifier: 'codeincolor'

services:
  codein.ezcolorpikcerbundle.fieldtype.codeincolor:
    parent: Ibexa\Core\FieldType\FieldType
    class: Codein\eZColorPicker\FieldType\ColorPicker\Type
    calls:
      - [ 'setColorConverter', [ "@codein.ezcolorpikcerbundle.colorconverter" ] ]
    tags:
      - { name: ibexa.field_type, alias: "%codein.fieldtype.color.identifier%" }
      - { name: ibexa.field_type.nameable, alias: "%codein.fieldtype.color.identifier%" }
  codein.ezcolorpikcerbundle.fieldtype.converter:
          class: Codein\eZColorPicker\FieldType\ColorPicker\LegacyConverter
          tags:
            - { name: ibexa.storageEngine.legacy.converter, alias: "%codein.fieldtype.color.identifier%" }
  codein.ezcolorpikcerbundle.fieldtype.form_mapper:
          class: Codein\eZColorPicker\FieldType\ColorPicker\FormMapper
          tags:
            - { name: ez.fieldFormMapper.value, fieldType: "%codein.fieldtype.color.identifier%" }
            - { name: ez.fieldFormMapper.definition, fieldType: "%codein.fieldtype.color.identifier%" }
  codein.ezcolorpikcerbundle.fieldtype.unindexed:
    class: eZ\Publish\Core\FieldType\Unindexed
    tags:
      - { name: ibexa.field_type.indexable, alias: "%codein.fieldtype.color.identifier%" }